const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
const GET_TAGS_REQUEST_SUCCESS = 'GET_TAGS_REQUEST_SUCCESS';
const GET_TAGS_REQUEST_FAILURE = 'GET_TAGS_REQUEST_FAILURE';
const TOGGLE_ACTIVE_TAG = 'TOGGLE_ACTIVE_TAG';

export default {
  GET_TAGS_REQUEST,
  GET_TAGS_REQUEST_SUCCESS,
  GET_TAGS_REQUEST_FAILURE,
  TOGGLE_ACTIVE_TAG,
};
