const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
const GET_TOPICS_REQUEST_SUCCESS = 'GET_TOPICS_REQUEST_SUCCESS';
const GET_TOPICS_REQUEST_FAILURE = 'GET_TOPICS_REQUEST_FAILURE';
const CHANGE_SELECTED_TOPIC = 'CHANGE_SELECTED_TOPIC';

export default {
  GET_TOPICS_REQUEST,
  GET_TOPICS_REQUEST_SUCCESS,
  GET_TOPICS_REQUEST_FAILURE,
  CHANGE_SELECTED_TOPIC,
};
