const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
const GET_TOPICS_REQUEST_SUCCESS = 'GET_TOPICS_REQUEST_SUCCESS';
const GET_TOPICS_REQUEST_FAILURE = 'GET_TOPICS_REQUEST_FAILURE';

export default {
  GET_TOPICS_REQUEST,
  GET_TOPICS_REQUEST_SUCCESS,
  GET_TOPICS_REQUEST_FAILURE,
};
